[package]
name = "subway-eat-fresh"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
dotenvy = "0.15.7"
envy = "0.4.2"
hex = "0.4.3"
serde = "1.0.209"
solana-client = "2.0.8"
solana-sdk = "2.0.8"
solana-transaction-status = "2.0.8"
